export const users = 'users'
export const friendInvites = 'friendInvites'
export const friendList = 'friendList'
export const invitesToPlay = 'invitesToPlay'
export const lobbies = 'lobbies'
export const lobbiesReady = 'lobbiesReady'