import FotoTankprof from '../../src/assets/players/eu.png'

export const players = [
  {
    name: "Lincoln",
    lastName: "Carvalho",
    nick: "Tankprof",
    steam: "https://steamcommunity.com/id/Tankprof/",
    steamID: "STEAM_0:0:54067554",
    avatar: FotoTankprof,
  },
  {
    name: "Jinho",
    lastName: "Franco",
    nick: "jiNhooo;",
    steam: "https://steamcommunity.com/id/jiNhooo",
    steamID: "STEAM_0:0:9541513",
    avatar: "../../src/assets/players/jinho.png",
  },
  {
    name: "Breno",
    lastName: "Gazi",
    nick: "Alien",
    steam: "https://steamcommunity.com/id/bbalien",
    steamID: "STEAM_0:1:163351691",
    avatar: "../../src/assets/players/alien.png",
  },
  {
    name: "Willian",
    lastName: "Pinheiro",
    nick: "WillCRK",
    steam: "https://steamcommunity.com/profiles/76561198045395912",
    steamID: "STEAM_0:0:42565092",
    avatar: "../../src/assets/players/will.png",
  },
  {
    name: "Danilo",
    lastName: "Bueno",
    nick: "daoXP",
    steam: "https://steamcommunity.com/id/danilodao",
    steamID: "STEAM_0:0:228026000",
    avatar: "../../src/assets/players/dao.png",
  },
  {
    name: "Breno",
    lastName: "Rossine",
    nick: "coLBlind",
    steam: "https://steamcommunity.com/profiles/76561198823866057",
    steamID: "",
    avatar: "../../src/assets/players/rossini.png",
  },
  {
    name: "Victor",
    lastName: "Mota",
    nick: "ONEMOTA-TAPS",
    steam: "https://steamcommunity.com/id/Onemota1",
    steamID: "STEAM_0:0:531636198",
    avatar: "../../src/assets/players/motta.png",
  },
  {
    name: "Rafael",
    lastName: "Santos",
    nick: "RafZenz",
    steam: "https://steamcommunity.com/id/rafzenz",
    steamID: "STEAM_0:0:210160962",
    avatar: "../../src/assets/players/rafa.jpg",
  },
  {
    name: "Gustavo",
    lastName: "Simões",
    nick: "portuga",
    steam: "https://steamcommunity.com/profiles/76561198048276395",
    steamID: "STEAM_0:1:44005333",
    avatar: "../../src/assets/players/simoes.jpg",
  },
  {
    name: "Lucas",
    lastName: "Segala",
    nick: "Segala!?",
    steam: "https://steamcommunity.com/profiles/76561198954563779",
    steamID: "STEAM_0:1:497149025",
    avatar: "../../src/assets/players/segalla.png",
  },
  {
    name: "Matheus",
    lastName: "Iugas",
    nick: "Droga é o Braia",
    steam: "https://steamcommunity.com/id/Iugas",
    steamID: "STEAM_0:1:21971468",
    avatar: "../../src/assets/players/iugas.png",
  },
  {
    name: "Thiago",
    lastName: "Becker",
    nick: "Beckerrr",
    steam: "https://steamcommunity.com/id/BkrT-",
    steamID: "STEAM_0:1:54294926",
    avatar: "../../src/assets/players/backer.jpg",
  },
  {
    name: "Rodrigo",
    lastName: "Emidinho",
    nick: "emidinhu",
    steam: "https://steamcommunity.com/profiles/76561197988016364",
    steamID: "STEAM_0:0:13875318",
    avatar: "../../src/assets/players/emidinho.jpg",
  },
  {
    name: "Marcella",
    lastName: "Marcucci",
    nick: "✿ Rosinha ♥",
    steam: "https://steamcommunity.com/id/mamarcucci",
    steamID: "STEAM_0:0:194512094",
    avatar: "../../src/assets/players/ma.png",
  },
  {
    name: "Matheus",
    lastName: "Marques",
    nick: "ÐogmA",
    steam: "https://steamcommunity.com/profiles/76561198062409874",
    steamID: "76561198062409874",
    avatar: "../../src/assets/players/matheus.png",
  },
  {
    name: "Guilherme",
    lastName: "Trindade",
    nick: "Peluda",
    steam: "https://steamcommunity.com/profiles/76561198072909890/",
    steamID: "STEAM_0:0:56322081",
    avatar: "../../src/assets/players/peluda.png",
  },
  {
    name: "Eduardo",
    lastName: "Rossi",
    nick: "",
    steam: "",
    steamID: "",
    avatar: "",
  },
];
